package flags

const (
	LogLevel         = "log-level"
	Seeds            = "seeds"
	Host             = "host"
	ListenerName     = "listener-name"
	User             = "user"
	Password         = "password"
	Namespace        = "namespace"
	Sets             = "sets"
	IndexName        = "index-name"
	VectorField      = "vector-field"
	Dimension        = "dimension"
	DistanceMetric   = "distance-metric"
	IndexMeta        = "index-meta"
	Timeout          = "timeout"
	Verbose          = "verbose"
	StorageNamespace = "storage-namespace"
	StorageSet       = "storage-set"
	MaxEdges         = "hnsw-max-edges"
	ConstructionEf   = "hnsw-ef-construction"
	Ef               = "hnsw-ef"
	BatchMaxRecords  = "hnsw-batch-max-records"
	BatchInterval    = "hnsw-batch-interval"
	BatchEnabled     = "hnsw-batch-enabled"
	TLSProtocols     = "tls-protocols"
	TLSCaFile        = "tls-cafile"
	TLSCaPath        = "tls-capath"
	TLSCertFile      = "tls-certfile"
	TLSKeyFile       = "tls-keyfile"
	TLSKeyFilePass   = "tls-keyfile-password"
)
