name: Check Markdown and Help Text Links
permissions:
  contents: read
  pull-requests: write
on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # v1.0.16
      with:
        use-quiet-mode: yes
        file-extension: .md
    - uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # v1.0.16
      with:
        use-quiet-mode: yes
        file-extension: .go
        