name: Test
on:
  push:
    branches-ignore:
      - main
  workflow_call:
  
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get go version from go.mod
      run: |
        echo "GO_VERSION=$(grep '^go ' go.mod | cut -d " " -f 2)" >> $GITHUB_ENV
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Write feature keys
      env:
        FEATURES_CONF : ${{secrets.FEATURES_CONF}}

      run: |
        echo "$FEATURES_CONF" > docker/config/features.conf
    - name: Run tests
      run: |
        make coverage
    # - name: Upload coverage to Codecov // Add when public
    #   uses: codecov/codecov-action@v3
    #   with:
    #     token: ${{secrets.CODECOV_TOKEN}}
    #     files: testdata/coverage/total.cov
    #     verbose: false
