name: Test
on:
  push:
    branches:
      - '**'  # Run on every branch
  pull_request:
    branches-ignore:
      - '**'  # Ignore all branches for pull requests
  workflow_call:
  
jobs:
  tests:
    runs-on: aerospike_large_runners_8
    steps:
    - uses: actions/checkout@v3
    - name: Get go version from go.mod
      run: |
        echo "GO_VERSION=$(grep '^go ' go.mod | cut -d " " -f 2)" >> $GITHUB_ENV
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Write feature keys
      env:
        FEATURES_CONF : ${{secrets.FEATURES_CONF}}

      run: |
        echo "$FEATURES_CONF" > docker/vanilla/config/features.conf
        echo "$FEATURES_CONF" > docker/tls/config/features.conf
        echo "$FEATURES_CONF" > docker/mtls/config/features.conf
        echo "$FEATURES_CONF" > docker/auth/config/features.conf
    - name: Login to Aerospike Jfrog
      run: |
        echo "${{ secrets.JFROG_ACCESS_TOKEN }}" | docker login aerospike.jfrog.io -u "${{ secrets.JFROG_USERNAME }}" --password-stdin
    - name: Run tests
      run: |
        FAIL_FAST=true make test